# Default values for hzero-swagger.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.choerodon.com.cn/hzero-hzero/hzero-swagger
  pullPolicy: Always

preJob:
  image: registry.cn-hangzhou.aliyuncs.com/choerodon-tools/dbtool:0.6.2
  timeout: 1200
  preInitDB:
    enable: false
    datasource:
      url: jdbc:mysql://db.hzero.org:3306/hzero_admin?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: hzero
      password: hzero

deployment:
  managementPort: 8051

env:
  open:
    # Eureka 注册中心地址
    EUREKA_DEFAULT_ZONE: http://dev.hzero.org:8000/eureka/
    # 服务以IP地址注册
    EUREKA_INSTANCE_PREFER_IP_ADDRESS: true
    # 是否启用配置中心
    SPRING_CLOUD_CONFIG_ENABLED: false
    # 配置中心地址
    SPRING_CLOUD_CONFIG_URI: http://dev.hzero.org:8010/
    # 数据库地址
    SPRING_DATASOURCE_URL: jdbc:mysql://db.hzero.org:3306/hzero_governance?useUnicode=true&characterEncoding=utf-8&useSSL=false
    # 数据库用户名
    SPRING_DATASOURCE_USERNAME: hzero
    # 数据库密码
    SPRING_DATASOURCE_PASSWORD: hzero
    # 连接池最小空闲连接数
    SPRING_DATASOURCE_MINIMUM_IDLE: 20
    # 连接池允许的最大连接数
    SPRING_DATASOURCE_MAXIMUM_POOL_SIZE: 200
    # 等待连接池分配连接的最大时长（毫秒）
    SPRING_DATASOURCE_CONNECTION_TIMEOUT: 30000
    # Redis地址
    SPRING_REDIS_HOST: redis.hzero.org
    # Redis端口
    SPRING_REDIS_PORT: 6379
    # Redis数据库
    SPRING_REDIS_DATABASE: 1
    # 资源池中最大连接数
    # 默认8，-1表示无限制；可根据服务并发redis情况及服务端的支持上限调整
    SPRING_REDIS_POOL_MAX_ACTIVE: 50
    # 资源池运行最大空闲的连接数
    # 默认8，-1表示无限制；可根据服务并发redis情况及服务端的支持上限调整，一般建议和max-active保持一致，避免资源伸缩带来的开销
    SPRING_REDIS_POOL_MAX_IDLE: 50
    # 当资源池连接用尽后，调用者的最大等待时间(单位为毫秒)
    # 默认 -1 表示永不超时，设置5秒
    SPRING_REDIS_POOL_MAX_WAIT: 5000
    # Hystrix 熔断超时时间
    HYSTRIX_COMMAND_TIMEOUT_IN_MILLISECONDS: 40000
    # Swagger Client ID
    HZERO_SWAGGER_CLIENT: client
    # Oauth地址
    HZERO_OAUTH_URL: http://dev.hzero.org/oauth/oauth/authorize
    # Swagger忽略服务
    HZERO_SWAGGER_SKIP_SERVICE: register, gateway, oauth
    # 网关域
    HZERO_GATEWAY_DOMAIN: dev.hzero.org:8080
    # Swagger支持协议
    HZERO_SWAGGER_PROTOCOLS: http
    # Swagger获取文档次数
    HZERO_SWAGGER_FETCH_TIME: 20
    # Swagger获取文档时间（秒）
    HZERO_SWAGGER_FETCH_SECONDS: 30
    # 日志级别
    LOG_LEVEL: info
    JAVA_OPTS: >
      -Xms1024m
      -Xmx1536m

metrics:
  path: /actuator/prometheus
  group: spring-boot

logs:
  parser: spring-boot

persistence:
  enabled: false

service:
  enabled: false
  type: ClusterIP
  port: 8050
  name: hzero-swagger
  
ingress:
  enabled: false

resources:
  limits:
    memory: 1.7Gi
  requests:
    memory: 1.2Gi
hzero:
  HZERO_NODE_GROUP_ID: 0
  HZERO_PRODUCT_CODE: DEFAULT
  HZERO_PRODUCT_VERSION_CODE: DEFAULT
  HZERO_PRODUCT_ENV_CODE: DEFAULT
  HZERO_SERVICE_VERSION_CODE: DEFAULT
