server:
  port: 9010

spring:
  application:
    name: microservice-monitroing-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://db.hzero.org:3306/hzero_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:hzero}
    password: ${SPRING_DATASOURCE_PASSWORD:hzero}
    hikari:
      # 连接池最小空闲连接数
      minimum-idle: ${SPRING_DATASOURCE_MINIMUM_IDLE:20}
      # 连接池允许的最大连接数
      maximum-pool-size: ${SPRING_DATASOURCE_MAXIMUM_POOL_SIZE:200}
      # 等待连接池分配连接的最大时长（毫秒）
      connection-timeout: ${SPRING_DATASOURCE_CONNECTION_TIMEOUT:30000}
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.31.111:9300
      repositories:
        enabled: true

  # es
#  elasticsearch:
#    rest:
#      uris: http://192.168.31.111:9200
#      username: elactis
#      password: 123456
  #配置中心
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
    cloud:
      config:
        fail-fast: false
        # 是否启用配置中心
        enabled: ${SPRING_CLOUD_CONFIG_ENABLED:false}
        # 配置中心地址
        uri: ${SPRING_CLOUD_CONFIG_URI:http://dev.hzero.org:8010}
        retry:
          # 最大重试次数
          maxAttempts: 6
          multiplier: 1.1
          # 重试间隔时间
          maxInterval: 2000
        # 标签
        label: ${SPRING_CLOUD_CONFIG_LABEL:}
#注册中心
eureka:
  instance:
    # 以IP注册到注册中心
    preferIpAddress: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    # 服务的一些元数据信息
    metadata-map:
      VERSION: 1.3.1.RELEASE
  client:
    serviceUrl:
      # 注册中心地址
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://dev.hzero.org:8000/eureka}
    registryFetchIntervalSeconds: 10
    disable-delta: true


