# Default values for hzero-org.hzero.gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.choerodon.com.cn/hzero-hzero/hzero-org.hzero.gateway
  pullPolicy: Always

deployment:
  managementPort: 8081

env:
  open:
    # 项目级API是否必须检查项目参数
    HZERO_GATEWAY_FILTER_COMMON_REQUEST_CHECK_PROJECT: true
    # 组织级API是否必须检查组织参数
    HZERO_GATEWAY_FILTER_COMMON_REQUEST_CHECK_ORGANIZATION: true
    # 是否启用标准的权限检查
    HZERO_GATEWAY_FILTER_COMMON_REQUEST_ENABLE: true
    # 是否统计API访问情况
    HZERO_GATEWAY_FILTER_COLLECT_SPAN_ENABLED: false
    # 是否打印 JWT
    HZERO_GATEWAY_HELPER_ENABLE_JWT_LOG: false
    EUREKA_DEFAULT_ZONE: http://dev.hzero.org:8000/eureka/
    EUREKA_INSTANCE_PREFER_IP_ADDRESS: true
    SPRING_CLOUD_CONFIG_ENABLED: true
    SPRING_CLOUD_CONFIG_URI: http://dev.hzero.org:8010/
    SPRING_REDIS_HOST: 192.168.11.167
    SPRING_REDIS_PORT: 6379
    SPRING_REDIS_DATABASE: 4
    LOG_LEVEL: info
    JAVA_OPTS: >
      -Xms1024m
      -Xmx1536m

metrics:
  path: /actuator/prometheus
  group: spring-boot

logs:
  parser: spring-boot

persistence:
  enabled: false

service:
  enabled: false
  type: ClusterIP
  port: 8080
  name: hzero-org.hzero.gateway
  
ingress:
  enabled: false

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources,such as Minikube. If you do want to specify resources,uncomment the following
  # lines,adjust them as necessary,and remove the curly braces after 'resources:'.
  limits:
    # cpu: 100m
    memory: 1.7Gi
  requests:
    # cpu: 100m
    memory: 1.2Gi

hzero:
  HZERO_NODE_GROUP_ID: 0
  HZERO_PRODUCT_CODE: DEFAULT
  HZERO_PRODUCT_VERSION_CODE: DEFAULT
  HZERO_PRODUCT_ENV_CODE: DEFAULT
  HZERO_SERVICE_VERSION_CODE: DEFAULT